spring:
  application: praveenoruganti-ems-web
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
   jpa:
     show-sql: true 
     database: MYSQL
     generate-ddl: false
     
  datasource:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://root:password@localhost:3306/employeelogindb?reconnect=true
          username: root
          password: password
          hikari:
            connectionTimeout : 30000
            idleTimeout : 600000
            maxLifetime : 1800000
            maximumPoolSize : 5
 
server:
   port: 7100
   servlet:
    context-path: /ems
